module Transmission
  class RPC
    class SessionSet < Method

      mutator 'alt-speed-down'
      mutator 'alt-speed-enabled'
      mutator 'alt-speed-time-begin'
      mutator 'alt-speed-time-enabled'
      mutator 'alt-speed-time-end'
      mutator 'alt-speed-time-day'
      mutator 'alt-speed-up'
      mutator 'blocklist-url'
      mutator 'blocklist-enabled'
      mutator 'blocklist-size'
      mutator 'cache-size-mb'
      mutator 'config-dir'
      mutator 'download-dir'
      mutator 'download-queue-size'
      mutator 'download-queue-enabled'
      mutator 'dht-enabled'
      mutator 'encryption'
      mutator 'idle-seeding-limit'
      mutator 'idle-seeding-limit-enabled'
      mutator 'incomplete-dir'
      mutator 'incomplete-dir-enabled'
      mutator 'lpd-enabled'
      mutator 'peer-limit-global'
      mutator 'peer-limit-per-torrent'
      mutator 'pex-enabled'
      mutator 'peer-port'
      mutator 'peer-port-random-on-start'
      mutator 'port-forwarding-enabled'
      mutator 'queue-stalled-enabled'
      mutator 'queue-stalled-minutes'
      mutator 'rename-partial-files'
      mutator 'rpc-version'
      mutator 'rpc-version-minimum'
      mutator 'script-torrent-done-filename'
      mutator 'script-torrent-done-enabled'
      mutator 'seedRatioLimit'
      mutator 'seedRatioLimited'
      mutator 'seed-queue-size'
      mutator 'seed-queue-enabled'
      mutator 'speed-limit-down'
      mutator 'speed-limit-down-enabled'
      mutator 'speed-limit-up'
      mutator 'speed-limit-up-enabled'
      mutator 'start-added-torrents'
      mutator 'trash-original-torrent-files'
      mutator 'units'
      mutator 'utp-enabled'
      mutator 'version'

    end
  end
end
